name: dbt-instance
x-common-config:
  &dbt-common-config
  image: ghcr.io/dbt-labs/dbt-bigquery:1.8.2
  entrypoint: ["dbt"]
  volumes:
    - .:/usr/app
    - type: volume
      source: dbt_config
      target: /root/.dbt
      read_only: true

services:
  docs:
    <<: *dbt-common-config
    tty: true
    command:
      ["docs", "serve", "--port", "8080", "--host", "0.0.0.0"]
    ports:
      - "8881:8080"
    
volumes:
  dbt_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\Users\Maverick\.dbt

# Mount your Google Cloud credentials if using service account authentication
#   #     - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/gcp-credentials.json:ro