name: dbt-instance-dev

x-common-config:
  &dbt-common-config
  build:
    context: .
    dockerfile: Dockerfile-dev
  volumes:
    - ./seeds:${DBT_PROJECT_DIR}/seeds
    - ./logs:${DBT_PROJECT_DIR}/logs
  env_file:
    - .env
  secrets:
    - source: keyfile_secret
      target: ${DBT_PROFILES_DIR}/bq-keyfile.json
      mode: 0444

services:
  debug:
    <<: *dbt-common-config
    command: ["debug"]
  run:
    <<: *dbt-common-config
    profiles:
      - run
    command: ["run"]
  ui:
    <<: *dbt-common-config
    tty: true
    entrypoint: /bin/sh
    command: -c "dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"
    ports:
      - "${PORT_DBT_UI:-8888}:8080"

secrets:
  keyfile_secret:
    file: ./config/bq-keyfile.json