# IMPORTANT: For testing dbt before moving to docker compose airflow with dbt
# Check the configuration path.

name: dbt-instance
x-common-config:
  &dbt-common-config
  build: 
    context: .
    dockerfile: Dockerfile
  volumes:
    - ${DBT_PROJECT_DIR:-.}/analyses:${DBT_CONT_DIR:-/usr/app}/analyses
    - ${DBT_PROJECT_DIR:-.}/macros:${DBT_CONT_DIR:-/usr/app}/macros
    - ${DBT_PROJECT_DIR:-.}/models:${DBT_CONT_DIR:-/usr/app}/models
    - ${DBT_PROJECT_DIR:-.}/snapshots:${DBT_CONT_DIR:-/usr/app}/snapshots
    - ${DBT_PROJECT_DIR:-.}/seeds:${DBT_CONT_DIR:-/usr/app}/seeds
    - ${DBT_PROJECT_DIR:-.}/tests:${DBT_CONT_DIR:-/usr/app}/tests
    - ${DBT_PROJECT_DIR:-.}/target:${DBT_CONT_DIR:-/usr/app}/target
    - ${DBT_PROJECT_DIR:-.}/dbt_project.yml:${DBT_CONT_DIR:-/usr/app}/dbt_project.yml
  env_file:
    - .env
  secrets:
    - bq_service_account_key

services:
  ui:
    <<: *dbt-common-config
    tty: true
    entrypoint: /bin/sh
    command: -c "dbt deps && dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"
    ports:
      - "${PORT_DBT_UI:-8888}:8080"
  
  debug:
    <<: *dbt-common-config
    tty: true
    entrypoint: /bin/sh
    command: -c "dbt deps && dbt debug"

  build:
    <<: *dbt-common-config
    profiles:
      - build
    command: ["build"]

networks:
  data_network:
    external: true

secrets:
  bq_service_account_key:
    file: ./config/bq-keyfile.json