# This is a Docker Compose file for a dbt instance using BigQuery in production.
# <project>_<service>_<environment>
name: general-dbt_bigquery-prod

x-common-config:
  &dbt-common-config
  build:
    context: .
    dockerfile: Dockerfile.dbt
  volumes:
    - ${DBT_CURRENT_DIR}/seeds:${DBT_PROJECT_DIR}/seeds
    - ${DBT_CURRENT_DIR}/logs:${DBT_PROJECT_DIR}/logs
  env_file:
    - .env
  secrets:
    - source: keyfile_secret
      target: ${DBT_PROFILES_DIR}/bq-keyfile.json
      mode: 0444
  networks:
    - dbt-network

services:
  debug: # Check if it can connect to the datawarehouse, etc.
    <<: *dbt-common-config
    command: ["debug"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  docs: # Check the lineage, models, seeds, etc.
    <<: *dbt-common-config
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: ["dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"]
    ports:
      - "${PORT_DBT_UI_PROD:-8888}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      debug:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  api:
    <<: *dbt-common-config
    entrypoint: ["uvicorn"]
    command: [
        "api.server:app",
        "--host", "0.0.0.0",
        "--port", "5000",
        "--workers", "2",
        "--log-level", "info"
      ]
    ports:
      - "${PORT_DBT_SERVER:-5051}:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      debug:
        condition: service_completed_successfully

  runner:
    <<: *dbt-common-config
    profiles:
      - debug
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 86400; done"] 
    restart: always
    depends_on:
      debug:
        condition: service_completed_successfully
    networks:
      - dbt-airflow-network

networks:
  dbt-network:
    driver: bridge
  dbt-airflow-network:
    external: true
    name: shared-dbt-airflow-network

secrets:
  keyfile_secret:
    file: ./config/bq-keyfile.json