name: dbt-instance

services:
  dbt:
    build: .
    volumes:
      - .:/usr/app
      - ~/.dbt:/root/.dbt
      # Mount your Google Cloud credentials if using service account authentication
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/gcp-credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/gcp-credentials.json
    command: >
      bash -c "dbt deps && dbt debug && dbt run"

  dbt-docs:
    build: .
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/usr/app
    #   - ~/.dbt:/root/.dbt
    #   - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/gcp-credentials.json:ro
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=/root/gcp-credentials.json
    command: >
      bash -c "dbt deps && dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"
