[project]
name = "bigquery-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "dbt-metricflow>=0.8.2",
]
