version: 2
sources:
  - name: bronze
    tables:
      - name: raw_seed_calendar
      - name: raw_seed_customers
      - name: raw_seed_overall_transactions
      - name: raw_seed_products
      - name: raw_seed_regions
      - name: raw_seed_returns
      - name: raw_seed_stores