bigquery-general-profile:
  target: bronze

  outputs:
    bronze:
      type: bigquery
      method: service-account
      project: "bqtest-444723"
      dataset: bronze
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json
    
    silver:
      type: bigquery
      method: service-account
      project: "bqtest-444723"
      dataset: silver
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json
      
    gold:
      type: bigquery
      method: service-account
      project: "bqtest-444723"
      dataset: gold
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json
        
    marts:
      type: bigquery
      method: service-account
      project: "bqtest-444723"
      dataset: gold
      threads: 4
      keyfile: /root/.dbt/bq-keyfile.json
      