version: 2
sources:
  - name: bronze
    tables:
      - name: Calendar
      - name: Customers
      - name: Overall_Transactions
      - name: Products
      - name: Regions
      - name: Returns
      - name: Stores