name: Sync Main to Hotfix

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Prevent concurrent runs for the same branch to avoid race conditions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Main -> Hotfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Fetch all history and branches, not just the triggering commit
          fetch-depth: 0
          # Use a token with write permissions
          # The default GITHUB_TOKEN often works if repo settings allow workflow write access
          # Otherwise, use a PAT stored as a secret: token: ${{ secrets.YOUR_PAT_SECRET }}

      - name: Set up Git User
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"

      - name: Switch to Hotfix Branch
        run: git checkout hotfix

      - name: Ensure Hotfix is Up-to-Date with Remote
        run: git pull origin hotfix # Ensures local hotfix is current before merge

      - name: Merge Main into Hotfix
        run: |
          # Attempt to merge main into the current branch (hotfix)
          # --no-ff: Creates a merge commit even if fast-forward is possible (optional, but can be clearer)
          # --no-edit: Uses the default merge commit message without opening an editor
          git merge origin/main --no-ff --no-edit
        # If merge conflicts occur, this step will fail the workflow

      - name: Push Changes to Hotfix
        run: git push origin hotfix

      # Optional: Handle Merge Conflicts (Basic Notification)
      # This step runs only if the merge step failed
      - name: Notify on Merge Conflict
        if: failure() && steps.merge.outcome == 'failure' # Check if the specific merge step failed
        run: |
          echo "::error::Merge conflict detected when merging main into hotfix. Manual resolution required."
          # You could add more advanced notifications here (e.g., Slack, issue creation)
          exit 1 # Ensure the job fails explicitly